### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by mickovski** [mickovski/filter#1]
**What are we optimizing?**
- Use rate of return >> in top or bottom 10%
- time period is Quarter

**What data are we going to use?**
- Bloomberg, maybe from 2011 to 2015

**Model**
- use decision tree
- want to find the depth of tree
- can use package to do decision tree

target is 1 if rr is in top 10%, 0 otherwise

- use train and validation set to find the optimal depth of tree

**What to plot?**
- plot % of the top10% vs score(from 1 to 0) [continuous]
- plot % of the top10% in a bin vs score(from 1 to 0[discrete]

![img_5593](https://user-images.githubusercontent.com/26858310/36081322-359dc472-0f6b-11e8-8ad3-cb53d537c869.jpg)

**Comment by bubblesort251** [comment]
This is all correct / useful.  I moved the information to a README.md file so that if shows up on the front page
